### PR TITLE
connectome2tck: Skip non-valid exemplars

### LINKED ISSUE #1769: mrview crashes during connectome visalisation
when I want to visualize connectome connections using streamline visualisation on my data, mrview suddenly crashes. 
However, this did work on my test data which was processed locally. mrview crashes on the actual data, which was processed in the same way but on an hpc.

<details> 
  <summary>Q1: The full debug output: </summary>

```
Jeroen:connectome jblomm6$ mrview Pat_034_wmodf_firstsh.nii.gz -debug
mrview: [DEBUG] No config file found at "/etc/mrtrix.conf"
mrview: [DEBUG] No config file found at "/Users/jblomm6/.mrtrix.conf"
mrview: [INFO] GL renderer:  AMD Radeon Pro 560X OpenGL Engine
mrview: [INFO] GL version:   4.1 ATI-2.11.20
mrview: [INFO] GL vendor:    ATI Technologies Inc.
mrview: [DEBUG] loading font into OpenGL texture...
mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout(location = 0) in vec2 pos;
layout(location = 1) in vec2 font_pos;
uniform float scale_x;
uniform float scale_y;
out vec2 tex_coord;
void main () {
  gl_Position = vec4 (pos[0]*scale_x-1.0, pos[1]*scale_y-1.0, 0.0, 1.0);
  tex_coord = font_pos;
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
in vec2 tex_coord;
uniform sampler2D sampler;
uniform float red, green, blue;
out vec4 color;
void main () {
  color.ra = texture (sampler, tex_coord).rg;
  color.rgb = color.r * vec3 (red, green, blue);
}

mrview: [DEBUG] font loaded
mrview: [INFO] opening image "Pat_034_wmodf_firstsh.nii.gz"...
mrview: [DEBUG] transforms_match: FOV difference in scanner coordinates: 1.9409983964656583e-06
mrview: [DEBUG] sanitising image information...
mrview: [INFO] image "Pat_034_wmodf_firstsh.nii.gz" opened with dimensions 185x185x96, voxel spacing 1.2999999523162842x1.2999999523162842x1.2999999523162842, datatype Float32LE
mrview: [DEBUG] loading image "Pat_034_wmodf_firstsh.nii.gz"...
mrview: [INFO] mrview: uncompressing image "Pat_034_wmodf_firstsh.nii.gz"
mrview: [INFO] mrview: uncompressing image "Pat_034_wmodf_firstsh.nii.gz" [done]
mrview: [DEBUG] image "Pat_034_wmodf_firstsh.nii.gz" loaded
mrview: [DEBUG] image "Pat_034_wmodf_firstsh.nii.gz" initialised with strides = [ 1 185 34225 ], start = 0, using indirect IO
mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout(location = 0) in vec3 vertpos;
layout(location = 1) in vec3 texpos;
uniform mat4 MVP;
out vec3 texcoord;
void main() {
  gl_Position =  MVP * vec4 (vertpos,1);
  texcoord = texpos;
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
uniform float offset;
uniform float scale;
uniform sampler3D tex;
in vec3 texcoord;
out vec4 color;
void main() {
  if (texcoord.s < 0.0 || texcoord.s > 1.0 ||
      texcoord.t < 0.0 || texcoord.t > 1.0 ||
      texcoord.p < 0.0 || texcoord.p > 1.0) discard;
  color = texture (tex, texcoord.stp);
  float amplitude = color.r;
  if (isnan(amplitude) || isinf(amplitude)) discard;
  amplitude = clamp ( scale * (amplitude - offset), 0.0, 1.0);
  color.rgb = vec3 (amplitude);
}

mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout(location=0) in vec2 pos;
void main () {
  gl_Position = vec4 (pos, 0.0, 1.0);
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
out vec4 color;
void main () {
  color = vec4 (0.5, 0.5, 0.0, 1.0);
}

mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout(location=0) in vec3 data;
uniform float scale_x, scale_y;
out float amplitude;
void main () {
  gl_Position = vec4 (data.x*scale_x-1.0, data.y*scale_y-1.0, 0.0, 1.0);
  amplitude = data.z;
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
in float amplitude;
out vec3 color;
uniform vec3 colourmap_colour;
void main () {
  color.rgb = vec3 (amplitude);
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
out vec3 color;
void main () {
  color = vec3(1.0, 1.0, 0.0);
}

mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout (location = 0) in vec3 vertexPosition_modelspace;
uniform mat4 MVP;
uniform mat4 MV;
uniform vec3 node_centre;
uniform float node_size;
out vec3 normal;
void main() {
  vec3 pos = node_centre + (vertexPosition_modelspace * node_size);
  normal = normalize (mat3(MV) * vertexPosition_modelspace);
  gl_Position = MVP * vec4 (pos, 1);
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
uniform vec3 node_colour;
out vec3 color;
uniform float ambient, diffuse, specular, shine;
uniform vec3 light_pos;
in vec3 normal;
void main() {
  color = node_colour;
  color *= ambient + diffuse * clamp (dot (normal, light_pos), 0, 1);
  color += specular * pow (clamp (dot (reflect (-light_pos, normal), vec3(0.0,0.0,1.0)), 0, 1), shine);
}

mrview: [DEBUG] compiling OpenGL vertex shader:
#version 330 core
layout (location = 0) in vec3 vertexPosition_modelspace;
uniform mat4 MVP;
uniform mat4 MV;
layout (location = 1) in vec3 vertexTangent_modelspace;
out vec3 tangent;
void main() {
  vec3 pos = vertexPosition_modelspace;
  tangent = normalize (mat3(MV) * vertexTangent_modelspace);
  gl_Position = MVP * vec4 (pos, 1);
}

mrview: [DEBUG] compiling OpenGL fragment shader:
#version 330 core
uniform vec3 edge_colour;
out vec3 color;
uniform float ambient, diffuse, specular, shine;
uniform vec3 light_pos;
in vec3 tangent;
void main() {
  color = edge_colour;
  vec3 t = normalize (tangent);
  float l_dot_t = dot(light_pos, t);
  vec3 l_perp = light_pos - l_dot_t * t;
  vec3 l_perp_norm = normalize (l_perp);
  float n_dot_t = t.z;
  vec3 n_perp = vec3(0.0, 0.0, 1.0) - n_dot_t * t;
  vec3 n_perp_norm = normalize (n_perp);
  float cos2_theta = 0.5+0.5*dot(l_perp_norm,n_perp_norm);
  color *= ambient + diffuse * length(l_perp) * cos2_theta;
  color += specular * sqrt(cos2_theta) * pow (clamp (-l_dot_t*n_dot_t + length(l_perp)*length(n_perp), 0, 1), shine);
}

mrview: [INFO] opening image "/Users/jblomm6/Documents/MRI/Processing/graph_theory/cerebral_palsy/data_141019/Pat_034/connectome/Pat_034_registered_fmriatlas_uint32.nii.gz"...
mrview: [DEBUG] transforms_match: FOV difference in scanner coordinates: 1.7060837305163112e-06
mrview: [DEBUG] sanitising image information...
mrview: [INFO] image "/Users/jblomm6/Documents/MRI/Processing/graph_theory/cerebral_palsy/data_141019/Pat_034/connectome/Pat_034_registered_fmriatlas_uint32.nii.gz" opened with dimensions 185x185x96, voxel spacing 1.2999999523162842x1.2999999523162842x1.2999999523162842, datatype UInt32LE
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 1 mask"...
mrview: [DEBUG] image "Node 1 mask" loaded
mrview: [DEBUG] image "Node 1 mask" initialised with strides = [ 1 18 486 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 2 mask"...
mrview: [DEBUG] image "Node 2 mask" loaded
mrview: [DEBUG] image "Node 2 mask" initialised with strides = [ 1 19 494 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 3 mask"...
mrview: [DEBUG] image "Node 3 mask" loaded
mrview: [DEBUG] image "Node 3 mask" initialised with strides = [ 1 29 725 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 4 mask"...
mrview: [DEBUG] image "Node 4 mask" loaded
mrview: [DEBUG] image "Node 4 mask" initialised with strides = [ 1 26 806 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 5 mask"...
mrview: [DEBUG] image "Node 5 mask" loaded
mrview: [DEBUG] image "Node 5 mask" initialised with strides = [ 1 32 768 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 6 mask"...
mrview: [DEBUG] image "Node 6 mask" loaded
mrview: [DEBUG] image "Node 6 mask" initialised with strides = [ 1 26 728 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 7 mask"...
mrview: [DEBUG] image "Node 7 mask" loaded
mrview: [DEBUG] image "Node 7 mask" initialised with strides = [ 1 27 810 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 8 mask"...
mrview: [DEBUG] image "Node 8 mask" loaded
mrview: [DEBUG] image "Node 8 mask" initialised with strides = [ 1 31 775 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 9 mask"...
mrview: [DEBUG] image "Node 9 mask" loaded
mrview: [DEBUG] image "Node 9 mask" initialised with strides = [ 1 32 768 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 10 mask"...
mrview: [DEBUG] image "Node 10 mask" loaded
mrview: [DEBUG] image "Node 10 mask" initialised with strides = [ 1 29 812 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 11 mask"...
mrview: [DEBUG] image "Node 11 mask" loaded
mrview: [DEBUG] image "Node 11 mask" initialised with strides = [ 1 26 754 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 12 mask"...
mrview: [DEBUG] image "Node 12 mask" loaded
mrview: [DEBUG] image "Node 12 mask" initialised with strides = [ 1 25 550 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 13 mask"...
mrview: [DEBUG] image "Node 13 mask" loaded
mrview: [DEBUG] image "Node 13 mask" initialised with strides = [ 1 31 806 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 14 mask"...
mrview: [DEBUG] image "Node 14 mask" loaded
mrview: [DEBUG] image "Node 14 mask" initialised with strides = [ 1 24 672 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 15 mask"...
mrview: [DEBUG] image "Node 15 mask" loaded
mrview: [DEBUG] image "Node 15 mask" initialised with strides = [ 1 21 546 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 16 mask"...
mrview: [DEBUG] image "Node 16 mask" loaded
mrview: [DEBUG] image "Node 16 mask" initialised with strides = [ 1 23 759 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 17 mask"...
mrview: [DEBUG] image "Node 17 mask" loaded
mrview: [DEBUG] image "Node 17 mask" initialised with strides = [ 1 23 621 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 18 mask"...
mrview: [DEBUG] image "Node 18 mask" loaded
mrview: [DEBUG] image "Node 18 mask" initialised with strides = [ 1 24 648 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 19 mask"...
mrview: [DEBUG] image "Node 19 mask" loaded
mrview: [DEBUG] image "Node 19 mask" initialised with strides = [ 1 26 572 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 20 mask"...
mrview: [DEBUG] image "Node 20 mask" loaded
mrview: [DEBUG] image "Node 20 mask" initialised with strides = [ 1 16 336 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 21 mask"...
mrview: [DEBUG] image "Node 21 mask" loaded
mrview: [DEBUG] image "Node 21 mask" initialised with strides = [ 1 33 957 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 22 mask"...
mrview: [DEBUG] image "Node 22 mask" loaded
mrview: [DEBUG] image "Node 22 mask" initialised with strides = [ 1 20 600 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 23 mask"...
mrview: [DEBUG] image "Node 23 mask" loaded
mrview: [DEBUG] image "Node 23 mask" initialised with strides = [ 1 25 675 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 24 mask"...
mrview: [DEBUG] image "Node 24 mask" loaded
mrview: [DEBUG] image "Node 24 mask" initialised with strides = [ 1 27 729 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 25 mask"...
mrview: [DEBUG] image "Node 25 mask" loaded
mrview: [DEBUG] image "Node 25 mask" initialised with strides = [ 1 23 529 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 26 mask"...
mrview: [DEBUG] image "Node 26 mask" loaded
mrview: [DEBUG] image "Node 26 mask" initialised with strides = [ 1 23 713 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 27 mask"...
mrview: [DEBUG] image "Node 27 mask" loaded
mrview: [DEBUG] image "Node 27 mask" initialised with strides = [ 1 26 754 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 28 mask"...
mrview: [DEBUG] image "Node 28 mask" loaded
mrview: [DEBUG] image "Node 28 mask" initialised with strides = [ 1 22 638 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 29 mask"...
mrview: [DEBUG] image "Node 29 mask" loaded
mrview: [DEBUG] image "Node 29 mask" initialised with strides = [ 1 31 775 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 30 mask"...
mrview: [DEBUG] image "Node 30 mask" loaded
mrview: [DEBUG] image "Node 30 mask" initialised with strides = [ 1 26 754 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 31 mask"...
mrview: [DEBUG] image "Node 31 mask" loaded
mrview: [DEBUG] image "Node 31 mask" initialised with strides = [ 1 27 702 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 32 mask"...
mrview: [DEBUG] image "Node 32 mask" loaded
mrview: [DEBUG] image "Node 32 mask" initialised with strides = [ 1 24 624 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 33 mask"...
mrview: [DEBUG] image "Node 33 mask" loaded
mrview: [DEBUG] image "Node 33 mask" initialised with strides = [ 1 30 750 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 34 mask"...
mrview: [DEBUG] image "Node 34 mask" loaded
mrview: [DEBUG] image "Node 34 mask" initialised with strides = [ 1 21 525 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 35 mask"...
mrview: [DEBUG] image "Node 35 mask" loaded
mrview: [DEBUG] image "Node 35 mask" initialised with strides = [ 1 24 576 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 36 mask"...
mrview: [DEBUG] image "Node 36 mask" loaded
mrview: [DEBUG] image "Node 36 mask" initialised with strides = [ 1 31 1054 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 37 mask"...
mrview: [DEBUG] image "Node 37 mask" loaded
mrview: [DEBUG] image "Node 37 mask" initialised with strides = [ 1 27 567 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 38 mask"...
mrview: [DEBUG] image "Node 38 mask" loaded
mrview: [DEBUG] image "Node 38 mask" initialised with strides = [ 1 27 648 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 39 mask"...
mrview: [DEBUG] image "Node 39 mask" loaded
mrview: [DEBUG] image "Node 39 mask" initialised with strides = [ 1 21 756 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 40 mask"...
mrview: [DEBUG] image "Node 40 mask" loaded
mrview: [DEBUG] image "Node 40 mask" initialised with strides = [ 1 27 837 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 41 mask"...
mrview: [DEBUG] image "Node 41 mask" loaded
mrview: [DEBUG] image "Node 41 mask" initialised with strides = [ 1 29 696 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 42 mask"...
mrview: [DEBUG] image "Node 42 mask" loaded
mrview: [DEBUG] image "Node 42 mask" initialised with strides = [ 1 23 552 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 43 mask"...
mrview: [DEBUG] image "Node 43 mask" loaded
mrview: [DEBUG] image "Node 43 mask" initialised with strides = [ 1 21 546 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 44 mask"...
mrview: [DEBUG] image "Node 44 mask" loaded
mrview: [DEBUG] image "Node 44 mask" initialised with strides = [ 1 31 868 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 45 mask"...
mrview: [DEBUG] image "Node 45 mask" loaded
mrview: [DEBUG] image "Node 45 mask" initialised with strides = [ 1 22 616 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 46 mask"...
mrview: [DEBUG] image "Node 46 mask" loaded
mrview: [DEBUG] image "Node 46 mask" initialised with strides = [ 1 27 702 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 47 mask"...
mrview: [DEBUG] image "Node 47 mask" loaded
mrview: [DEBUG] image "Node 47 mask" initialised with strides = [ 1 31 868 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 48 mask"...
mrview: [DEBUG] image "Node 48 mask" loaded
mrview: [DEBUG] image "Node 48 mask" initialised with strides = [ 1 25 775 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 49 mask"...
mrview: [DEBUG] image "Node 49 mask" loaded
mrview: [DEBUG] image "Node 49 mask" initialised with strides = [ 1 30 750 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 50 mask"...
mrview: [DEBUG] image "Node 50 mask" loaded
mrview: [DEBUG] image "Node 50 mask" initialised with strides = [ 1 31 868 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 51 mask"...
mrview: [DEBUG] image "Node 51 mask" loaded
mrview: [DEBUG] image "Node 51 mask" initialised with strides = [ 1 26 624 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 52 mask"...
mrview: [DEBUG] image "Node 52 mask" loaded
mrview: [DEBUG] image "Node 52 mask" initialised with strides = [ 1 20 440 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 53 mask"...
mrview: [DEBUG] image "Node 53 mask" loaded
mrview: [DEBUG] image "Node 53 mask" initialised with strides = [ 1 18 486 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 54 mask"...
mrview: [DEBUG] image "Node 54 mask" loaded
mrview: [DEBUG] image "Node 54 mask" initialised with strides = [ 1 30 720 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 55 mask"...
mrview: [DEBUG] image "Node 55 mask" loaded
mrview: [DEBUG] image "Node 55 mask" initialised with strides = [ 1 26 702 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 56 mask"...
mrview: [DEBUG] image "Node 56 mask" loaded
mrview: [DEBUG] image "Node 56 mask" initialised with strides = [ 1 25 700 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 57 mask"...
mrview: [DEBUG] image "Node 57 mask" loaded
mrview: [DEBUG] image "Node 57 mask" initialised with strides = [ 1 23 575 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 58 mask"...
mrview: [DEBUG] image "Node 58 mask" loaded
mrview: [DEBUG] image "Node 58 mask" initialised with strides = [ 1 30 840 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 59 mask"...
mrview: [DEBUG] image "Node 59 mask" loaded
mrview: [DEBUG] image "Node 59 mask" initialised with strides = [ 1 23 667 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 60 mask"...
mrview: [DEBUG] image "Node 60 mask" loaded
mrview: [DEBUG] image "Node 60 mask" initialised with strides = [ 1 28 728 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 61 mask"...
mrview: [DEBUG] image "Node 61 mask" loaded
mrview: [DEBUG] image "Node 61 mask" initialised with strides = [ 1 27 702 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 62 mask"...
mrview: [DEBUG] image "Node 62 mask" loaded
mrview: [DEBUG] image "Node 62 mask" initialised with strides = [ 1 26 702 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 63 mask"...
mrview: [DEBUG] image "Node 63 mask" loaded
mrview: [DEBUG] image "Node 63 mask" initialised with strides = [ 1 29 957 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 64 mask"...
mrview: [DEBUG] image "Node 64 mask" loaded
mrview: [DEBUG] image "Node 64 mask" initialised with strides = [ 1 29 783 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 65 mask"...
mrview: [DEBUG] image "Node 65 mask" loaded
mrview: [DEBUG] image "Node 65 mask" initialised with strides = [ 1 25 400 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 66 mask"...
mrview: [DEBUG] image "Node 66 mask" loaded
mrview: [DEBUG] image "Node 66 mask" initialised with strides = [ 1 25 700 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 67 mask"...
mrview: [DEBUG] image "Node 67 mask" loaded
mrview: [DEBUG] image "Node 67 mask" initialised with strides = [ 1 28 672 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 68 mask"...
mrview: [DEBUG] image "Node 68 mask" loaded
mrview: [DEBUG] image "Node 68 mask" initialised with strides = [ 1 23 552 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 69 mask"...
mrview: [DEBUG] image "Node 69 mask" loaded
mrview: [DEBUG] image "Node 69 mask" initialised with strides = [ 1 26 806 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 70 mask"...
mrview: [DEBUG] image "Node 70 mask" loaded
mrview: [DEBUG] image "Node 70 mask" initialised with strides = [ 1 28 644 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 71 mask"...
mrview: [DEBUG] image "Node 71 mask" loaded
mrview: [DEBUG] image "Node 71 mask" initialised with strides = [ 1 28 644 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 72 mask"...
mrview: [DEBUG] image "Node 72 mask" loaded
mrview: [DEBUG] image "Node 72 mask" initialised with strides = [ 1 26 806 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 73 mask"...
mrview: [DEBUG] image "Node 73 mask" loaded
mrview: [DEBUG] image "Node 73 mask" initialised with strides = [ 1 24 720 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 74 mask"...
mrview: [DEBUG] image "Node 74 mask" loaded
mrview: [DEBUG] image "Node 74 mask" initialised with strides = [ 1 27 675 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 75 mask"...
mrview: [DEBUG] image "Node 75 mask" loaded
mrview: [DEBUG] image "Node 75 mask" initialised with strides = [ 1 21 399 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 76 mask"...
mrview: [DEBUG] image "Node 76 mask" loaded
mrview: [DEBUG] image "Node 76 mask" initialised with strides = [ 1 27 702 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 77 mask"...
mrview: [DEBUG] image "Node 77 mask" loaded
mrview: [DEBUG] image "Node 77 mask" initialised with strides = [ 1 21 651 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 78 mask"...
mrview: [DEBUG] image "Node 78 mask" loaded
mrview: [DEBUG] image "Node 78 mask" initialised with strides = [ 1 27 729 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 79 mask"...
mrview: [DEBUG] image "Node 79 mask" loaded
mrview: [DEBUG] image "Node 79 mask" initialised with strides = [ 1 24 648 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 80 mask"...
mrview: [DEBUG] image "Node 80 mask" loaded
mrview: [DEBUG] image "Node 80 mask" initialised with strides = [ 1 32 704 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 81 mask"...
mrview: [DEBUG] image "Node 81 mask" loaded
mrview: [DEBUG] image "Node 81 mask" initialised with strides = [ 1 23 782 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 82 mask"...
mrview: [DEBUG] image "Node 82 mask" loaded
mrview: [DEBUG] image "Node 82 mask" initialised with strides = [ 1 22 748 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 83 mask"...
mrview: [DEBUG] image "Node 83 mask" loaded
mrview: [DEBUG] image "Node 83 mask" initialised with strides = [ 1 22 484 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 84 mask"...
mrview: [DEBUG] image "Node 84 mask" loaded
mrview: [DEBUG] image "Node 84 mask" initialised with strides = [ 1 31 651 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 85 mask"...
mrview: [DEBUG] image "Node 85 mask" loaded
mrview: [DEBUG] image "Node 85 mask" initialised with strides = [ 1 30 1110 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 86 mask"...
mrview: [DEBUG] image "Node 86 mask" loaded
mrview: [DEBUG] image "Node 86 mask" initialised with strides = [ 1 28 840 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 87 mask"...
mrview: [DEBUG] image "Node 87 mask" loaded
mrview: [DEBUG] image "Node 87 mask" initialised with strides = [ 1 35 875 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 88 mask"...
mrview: [DEBUG] image "Node 88 mask" loaded
mrview: [DEBUG] image "Node 88 mask" initialised with strides = [ 1 31 837 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 89 mask"...
mrview: [DEBUG] image "Node 89 mask" loaded
mrview: [DEBUG] image "Node 89 mask" initialised with strides = [ 1 31 899 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 90 mask"...
mrview: [DEBUG] image "Node 90 mask" loaded
mrview: [DEBUG] image "Node 90 mask" initialised with strides = [ 1 28 840 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 91 mask"...
mrview: [DEBUG] image "Node 91 mask" loaded
mrview: [DEBUG] image "Node 91 mask" initialised with strides = [ 1 29 667 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 92 mask"...
mrview: [DEBUG] image "Node 92 mask" loaded
mrview: [DEBUG] image "Node 92 mask" initialised with strides = [ 1 22 462 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 93 mask"...
mrview: [DEBUG] image "Node 93 mask" loaded
mrview: [DEBUG] image "Node 93 mask" initialised with strides = [ 1 32 928 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 94 mask"...
mrview: [DEBUG] image "Node 94 mask" loaded
mrview: [DEBUG] image "Node 94 mask" initialised with strides = [ 1 16 352 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 95 mask"...
mrview: [DEBUG] image "Node 95 mask" loaded
mrview: [DEBUG] image "Node 95 mask" initialised with strides = [ 1 23 621 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 96 mask"...
mrview: [DEBUG] image "Node 96 mask" loaded
mrview: [DEBUG] image "Node 96 mask" initialised with strides = [ 1 29 580 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 97 mask"...
mrview: [DEBUG] image "Node 97 mask" loaded
mrview: [DEBUG] image "Node 97 mask" initialised with strides = [ 1 22 550 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 98 mask"...
mrview: [DEBUG] image "Node 98 mask" loaded
mrview: [DEBUG] image "Node 98 mask" initialised with strides = [ 1 29 783 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 99 mask"...
mrview: [DEBUG] image "Node 99 mask" loaded
mrview: [DEBUG] image "Node 99 mask" initialised with strides = [ 1 31 713 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 100 mask"...
mrview: [DEBUG] image "Node 100 mask" loaded
mrview: [DEBUG] image "Node 100 mask" initialised with strides = [ 1 19 437 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 105 mask"...
mrview: [DEBUG] image "Node 105 mask" loaded
mrview: [DEBUG] image "Node 105 mask" initialised with strides = [ 1 48 2736 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 106 mask"...
mrview: [DEBUG] image "Node 106 mask" loaded
mrview: [DEBUG] image "Node 106 mask" initialised with strides = [ 1 47 2585 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 107 mask"...
mrview: [DEBUG] image "Node 107 mask" loaded
mrview: [DEBUG] image "Node 107 mask" initialised with strides = [ 1 10 190 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 108 mask"...
mrview: [DEBUG] image "Node 108 mask" loaded
mrview: [DEBUG] image "Node 108 mask" initialised with strides = [ 1 12 216 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 109 mask"...
mrview: [DEBUG] image "Node 109 mask" loaded
mrview: [DEBUG] image "Node 109 mask" initialised with strides = [ 1 7 49 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "Node 110 mask"...
mrview: [DEBUG] image "Node 110 mask" loaded
mrview: [DEBUG] image "Node 110 mask" initialised with strides = [ 1 7 42 ], start = 0, using direct IO
mrview: [DEBUG] initialising threads...
mrview: [DEBUG] launching 12 threads "loop threads"...
mrview: [DEBUG] waiting for completion of threads "loop threads"...
mrview: [DEBUG] threads "loop threads" completed OK
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] sanitising image information...
mrview: [DEBUG] allocating scratch buffer for image "node overlay scratch image"...
mrview: [DEBUG] image "node overlay scratch image" loaded
mrview: [DEBUG] image "node overlay scratch image" initialised with strides = [ 4 740 136900 1 ], start = 0, using direct IO
mrview: [DEBUG] reading key/value file "/Users/jblomm6/Documents/MRI/Processing/graph_theory/cerebral_palsy/data_141019/Pat_034/connectome/Pat_034_tracks4connectomevisualisation.tck"...
mrview: [INFO] mrview: Importing connection exemplars

mrview: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access
```

</details>

The tck files does not seem to be incorrect though.

Below the output of tckinfo and tckstats:

```
Jeroen:connectome jblomm6$ tckinfo Pat_034_tracks4connectomevisualisation.tck 
***********************************
  Tracks file: "Pat_034_tracks4connectomevisualisation.tck"
    count:                6105
    mrtrix_version:       unknown
    step_size:            0.649999976
    timestamp:            1570758538.6549372673
    total_count:          6105
Jeroen:connectome jblomm6$ tckstats Pat_034_tracks4connectomevisualisation.tck 
tckstats: [100%] Reading track file
tckstats: [WARNING] read 530 zero-length tracks
tckstats: [WARNING] expected 6105 tracks according to header; read 6549
         mean       median    std. dev.          min          max       count
      94.9473      95.2174      51.5389            0      281.024         6549
```

### PR DESCRIPTION
**Pull request by Lestropie**
Fixes #1769.

Cannot modify `mrview` to properly read data generated by `connectome2tck` prior to this fix, since the NaNs present in the track file make accurate parsing of the data impossible. However upon fixing the output of `connectome2tck`, no modification of `mrview` code was required in order to properly display these exemplars without assertion failure despite the absent parcels:

Screenshot from 2019-10-22 15-19-45

Thanks @JeroenBlommaert for the report.

### CODE REVIEW

File: src/dwi/tractography/connectome/exemplar.h [hunk 1]
```diff
@@ -35,12 +35,13 @@ class Exemplar : private Tractography::Streamline<float>
...
   public:
     using Tractography::Streamline<float>::point_type;
-    Exemplar (const size_t length, const NodePair& nodes, const std::pair<point_type, point_type>& COMs) :
+    Exemplar (const size_t exemplar_index, const size_t length, const NodePair& nodes, const std::pair<point_type, point_type>& COMs) :
         Tractography::Streamline<float> (length, { 0.0f, 0.0f, 0.0f }),
         nodes (nodes),
         node_COMs (COMs),
         is_finalized (false)
     {
+      index = exemplar_index;
```
Comment (jdtournier) [inline src/dwi/tractography/connectome/exemplar.h]: Why is this needed? It doesn't look like it's used anywhere else...

Comment (Lestropie) [reply src/dwi/tractography/connectome/exemplar.h]: Not needed; just distracting when you're trawling through `gdb` outputs trying to find the source of an issue, and you keep seeing streamlines that claim to have an index of one quadrillion or whatever.
