### PR TITLE
Attempted fixes to phase encoding handling

### LINKED ISSUE #2306: Image reorientation & external PE info
As raised on [forum](https://community.mrtrix.org/t/incorrect-phase-encoding-direction-after-dicom-import/4719).

Just as #1843 did for JSON-based orientation information, import & export of phase encoding information from & to text files needs to take into account either any internal image header reorientation that occurred at image load, or any reorientation that is to be applied to a NIfTI image that is to be exported at the same time as the phase encoding data.

I believe this should apply both to the `eddy`-style "config" / "index" data, and to straight 4-column 1-row-per-volume tabular data.

### PR DESCRIPTION
**Pull request by Lestropie**
If this doesn't fix #2306, then it should at least be close.

I'm pretty sure I can produce a comprehensive report of what works & what doesn't, but there's a lot of different use cases to test, and it's *very* easy to deceive yourself regarding what should actually correspond and what actually shouldn't. Anyone who has been having troubles with phase encoding data stored in external files can at least give this branch a try and see if it resolves their need to manually fix their data.

### CODE REVIEW

File: core/file/json_utils.cpp [hunk 1]
```diff
@@ -295,23 +288,15 @@ namespace MR
...
+          PhaseEncoding::set_scheme (H_adj, PhaseEncoding::transform_for_nifti_write (pe_scheme, header));
           INFO ("Phase encoding information written to JSON file modified according to expected output NIfTI header transform realignment");
         }
         auto slice_encoding_it = H_adj.keyval().find ("SliceEncodingDirection");
         if (slice_encoding_it != H_adj.keyval().end()) {
           const Eigen::Vector3 orig_dir (Axes::id2dir (slice_encoding_it->second));
           Eigen::Vector3 new_dir;
           for (size_t axis = 0; axis != 3; ++axis)
-            new_dir[axis] = header.stride (order[axis]) > 0 ? orig_dir[order[axis]] : -orig_dir[order[axis]];
+            new_dir[axis] = flip[axis] ? orig_dir[order[axis]] : -orig_dir[order[axis]];
```
Comment (Lestropie) [inline core/file/json_utils.cpp:299]: Note that this is not just a syntax change, it changes whether the binary flipping is considered to index axes after vs. before permutation. I'll hopefully confirm for phase encoding direction once I've done a comprehensive multi-parametric test. I'm not sure I have sufficient information in my test data to actually validate this for the direction of slice encoding, but it should just follow the same logic as that of the phase encoding table.

**Comment by Lestropie** [comment]
Okay, I've made an attempt at verifying this. I think the new code is correct, but would appreciate testing on real data where this has been causing problems, and attempts to find flaws in my logic.

-----

As with #1843, I have a set of 12 images of a phantom, acquired with each unique configuration of slice plane & phase encoding direction. On each of those images, I have manually edited the image intensities in order to indicate the direction of phase encoding. That edit was done with DICOM as input and MIH as output, with `-config RealignTransform false` set in the `mrcalc` call.

I then produce a set of testing images / sidecar data as follows:

- For each of: [ MIH, MIH with `-config RealignTransform false`, NII, NII with `-strides +1,+2,+3` ]:
    - Do an `mrconvert` call to that target format, with additional command-line options as necessary;
    - Additionally export a JSON;
    - Additionally export a PE table;
    - For NII outputs, additionally export `eddy`-style PE information

The tests enumerated in the raw data tables below are as follows:

1. `cat <image>.json | grep PhaseEncodingDirection`
2. `cat <image>_pe.txt`
3. (For NII only) `cat <image>_eddy.config`
4. `mrconvert <image>.<ext> -json_import <image>.json - | mrinfo - -property PhaseEncodingDirection`
5. `mrconvert <image>.<ext> -import_pe_table <image>_pe.txt - | mrinfo - -property PhaseEncodingDirection`
6. (For NII only) `mrconvert <image>.<ext> -import_pe_eddy <image>_eddy.config <image>_eddy.index - | mrinfo - -property PhaseEncodingDirection`
7. `mrview <image>.<ext> -config RealignTransform false`; manually observe the axis label & sign of voxel position change approaching fiducial
8. `mrview <image>.<ext>`; manually observe the axis label & sign of voxel position change approaching fiducial

## Conclusions:

- For all tests, visual confirmation of phase encoding direction via fiducial in `mrview` is correct, regardless of use of `-config RealignTransform false`
-  If `mrview` is opened with `-config RealignTransform false`, then the observed phase encoding direction is always identical to that specified in the sidecar data;
- On `master`, there can be an erroneous mismatch in the final interpretation of phase encoding information.
    It arises if one of the following are true:
    -  `-config RealignTransform false` is used during the initial conversion (presumably because that option is then *not* used later in the pipeline when querying that information, and the realignment had thus far been skipped);
    - Conversion target is NIfTI, and `-strides +1,+2,+3` is *not* used.
- PR code resolves those two issues, and (as far as I can tell) does not introduce any new issues elsewhere.
    - When `mrview` is used *without* `-config RealignTransform false`, then the observed phase encoding direction may be different to what's stored in such a file; but with PR code that observation is equivalent to what is interpreted regardless of whether those data were imported from JSON / PE table / `eddy` config-index files.
- As is somewhat described in the [phase encoding scheme handling](https://mrtrix.readthedocs.io/en/latest/concepts/pe_scheme.html) page (which might benefit from revision), it is possible to think that there is a problem with the phase encoding data when there is not, or vice-versa.
    There are *two* points at which an error may be introduced:
    - At image import, *if* *MRtrix3* modifies the image to approximate an axial acquisition (which occurs by default but can be disabled);
    - At NIfTI / MGH export, where *MRtrix3* forces the first three image axes to approximately correspond to L-R, P-A and I-S
respectively.
    
    If at any point, the *image data* undergo one of these manipulations, *but* the phase encoding information does *not* (whether due to being stored in sidecar files and erroneously omitted from the operation by the user, in the case of code prior to this PR due to the operations `-import_pe_*` and `-export_pe_*` erroneously not having those transformations applied, or due to looking at the image in `mrview` *without* `-config RealignTransform false` but reading the phase encoding information manually from a file rather than within the image properties in `mrview`), *and* if the transformation is not identity, the phase encoding information will no longer correspond.

---------------

## `master`:

#### MIH:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j- | `0 -1 0 0.05` | N/A | j- | j- | N/A | P (j-) | P (j-) |
| 003 Ax P>>A | j | `0 1 0 0.05` | N/A | j | j | N/A | A (j) | A (j) |
| 004 Ax R>>L | i- | `-1 0 0 0.05` | N/A | i- | i- | N/A | L (i-) | L (i-) |
| 005 Ax L>>R | i | `1 0 0 0.05` | N/A | i | i | N/A | R (i) | R (i) |
| 006 Cor R>>L | i- | `-1 0 0 0.05` | N/A | i- | i- | N/A | L (i-) | L (i-) |
| 007 Cor L>>R | i | `1 0 0 0.05` | N/A | i | i | N/A | R (i) | R (i) |
| 008 Cor H>>F | k- | `0 0 -1 0.05` | N/A | k- | k- | N/A | I (k-) | I (k-) |
| 009 Cor F>>H | k | `0 0 1 0.05` | N/A | k | k | N/A | S (k) | S (k) |
| 010 Sag A>>P | j- | `0 -1 0 0.05` | N/A | j- | j- | N/A | P (j-) | P (j-) |
| 011 Sag P>>A | j | `0 1 0 0.05` | N/A | j | j | N/A | A (j) | A (j) |
| 012 Sag H>>F | k- | `0 0 -1 0.05` | N/A | k- | k- | N/A | I (k-) | I (k-) |
| 013 Sag F>>H | k | `0 0 1 0.05` | N/A | k | k | N/A | S (k) | S (k) |

#### MIH with no reorientation:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j | `0 1 0 0.05` | N/A | j- | j | N/A | P (j) | P (j-) |
| 003 Ax P>>A | j- | `0 -1 0 0.05` | N/A | j | j- | N/A | A (j-) | A (j) |
| 004 Ax R>>L | i | `1 0 0 0.05` | N/A | i- | i | N/A | L (i) | L (i-) |
| 005 Ax L>>R | i- | `-1 0 0 0.05` | N/A | i | i- | N/A | R (i-) | R (i) |
| 006 Cor R>>L | i | `1 0 0 0.05` | N/A | i- | i | N/A | L (i) | L (i-) |
| 007 Cor L>>R | i- | `-1 0 0 0.05` | N/A | i | i- | N/A | R (i-) | R (i) |
| 008 Cor H>>F | j | `0 1 0 0.05` | N/A | k- | j | N/A | I (j) | I (k-) |
| 009 Cor F>>H | j- | `0 -1 0 0.05` | N/A | k | j- | N/A | S (j-) | S (k) |
| 010 Sag A>>P | i | `1 0 0 0.05` | N/A | j- | i | N/A | P (i) | P (j-) |
| 011 Sag P>>A | i- | `-1 0 0 0.05` | N/A | j | i- | N/A | A (i-) | A (j) |
| 012 Sag H>>F | j | `0 1 0 0.05` | N/A | k- | j | N/A | I (j) | I (k-) |
| 013 Sag F>>H | j- | `0 -1 0 0.05` | N/A | k | j- | N/A | S (j-) | S (k) |

#### NII:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j | `0 1 0 0.05` | `0 1 0 0.05` | j- | j | j | P (j) | P (j-) |
| 003 Ax P>>A | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | j | j- | j- | A (j-) | A (j) |
| 004 Ax R>>L | i | `1 0 0 0.05` | `1 0 0 0.05` | i- | i | i | L (i) | L (i-) |
| 005 Ax L>>R | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i | i- | i- | R (i-) | R (i) |
| 006 Cor R>>L | i | `1 0 0 0.05` | `1 0 0 0.05` | i- | i | i | L (i) | L (i-) |
| 007 Cor L>>R | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i | i- | i- | R (i-) | R (i) |
| 008 Cor H>>F | j | `0 1 0 0.05` | `0 1 0 0.05` | k- | j | j | I (j) | I (k-) |
| 009 Cor F>>H | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | k | j- | j- | S (j-) | S (k) |
| 010 Sag A>>P | i | `1 0 0 0.05` | `1 0 0 0.05` | j- | i | i | P (i) | P (j-) |
| 011 Sag P>>A | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | j | i- | i- | A (i-) | A (j) |
| 012 Sag H>>F | j | `0 1 0 0.05` | `0 1 0 0.05` | k- | j | j | I (j) | I (k-) |
| 013 Sag F>>H | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | k | j- | j- | S (j-) | S (k) |

#### NII with `-strides +1,+2,+3`:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | j- | j- | j- | P (j-) | P (j-) |
| 003 Ax P>>A | j | `0 1 0 0.05` | `0 1 0 0.05` | j | j | j | A (j) | A (j) |
| 004 Ax R>>L | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i- | i- | i- | L (i-) | L (i-) |
| 005 Ax L>>R | i | `1 0 0 0.05` | `1 0 0 0.05` | i | i | i | R (i) | R (i) |
| 006 Cor R>>L | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i- | i- | i- | L (i-) | L (i-) |
| 007 Cor L>>R | i | `1 0 0 0.05` | `1 0 0 0.05` | i | i | i | R (i) | R (i) |
| 008 Cor H>>F | k- | `0 0 -1 0.05` | `0 0 -1 0.05` | k- | k- | k- | I (k-) | I (k-) |
| 009 Cor F>>H | k | `0 0 1 0.05` | `0 0 1 0.05` | k | k | k | S (k) | S (k) |
| 010 Sag A>>P | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | j- | j- | j- | P (j-) | P (j-) |
| 011 Sag P>>A | j | `0 1 0 0.05` | `0 1 0 0.05` | j | j | j | A (j) | A (j) |
| 012 Sag H>>F | k- | `0 0 -1 0.05` | `0 0 -1 0.05` | k- | k- | k- | I (k-) | I (k-) |
| 013 Sag F>>H | k | `0 0 1 0.05` | `0 0 1 0.05` | k | k | k | S (k) | S (k) |

## PR code:

#### MIH:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j- | `0 -1 0 0.05` | N/A | j- | j- | N/A | P (j-) | P (j-) |
| 003 Ax P>>A | j | `0 1 0 0.05` | N/A | j | j | N/A | A (j) | A (j) |
| 004 Ax R>>L | i- | `-1 0 0 0.05` | N/A | i- | i- | N/A | L (i-) | L (i-) |
| 005 Ax L>>R | i | `1 0 0 0.05` | N/A | i | i | N/A | R (i) | R (i) |
| 006 Cor R>>L | i- | `-1 0 0 0.05` | N/A | i- | i- | N/A | L (i-) | L (i-) |
| 007 Cor L>>R | i | `1 0 0 0.05` | N/A | i | i | N/A | R (i) | R (i) |
| 008 Cor H>>F | k- | `0 0 -1 0.05` | N/A | k- | k- | N/A | I (k-) | I (k-) |
| 009 Cor F>>H | k | `0 0 1 0.05` | N/A | k | k | N/A | S (k) | S (k) |
| 010 Sag A>>P | j- | `0 -1 0 0.05` | N/A | j- | j- | N/A | P (j-) | P (j-) |
| 011 Sag P>>A | j | `0 1 0 0.05` | N/A | j | j | N/A | A (j) | A (j) |
| 012 Sag H>>F | k- | `0 0 -1 0.05` | N/A | k- | k- | N/A | I (k-) | I (k-) |
| 013 Sag F>>H | k | `0 0 1 0.05` | N/A | k | k | N/A | S (k) | S (k) |

#### MIH with no reorientation:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j | `0 1 0 0.05` | N/A | j- | j- | N/A | P (j) | P (j-) |
| 003 Ax P>>A | j- | `0 -1 0 0.05` | N/A | j | j | N/A | A (j-) | A (j) |
| 004 Ax R>>L | i | `1 0 0 0.05` | N/A | i- | i- | N/A | L (i) | L (i-) |
| 005 Ax L>>R | i- | `-1 0 0 0.05` | N/A | i | i | N/A | R (i-) | R (i) |
| 006 Cor R>>L | i | `1 0 0 0.05` | N/A | i- | i- | N/A | L (i) | L (i-) |
| 007 Cor L>>R | i- | `-1 0 0 0.05` | N/A | i | i | N/A | R (i-) | R (i) |
| 008 Cor H>>F | j | `0 1 0 0.05` | N/A | k- | k- | N/A | I (j) | I (k-) |
| 009 Cor F>>H | j- | `0 -1 0 0.05` | N/A | k | k | N/A | S (j-) | S (k) |
| 010 Sag A>>P | i | `1 0 0 0.05` | N/A | j- | j- | N/A | P (i) | P (j-) |
| 011 Sag P>>A | i- | `-1 0 0 0.05` | N/A | j | j | N/A | A (i-) | A (j) |
| 012 Sag H>>F | j | `0 1 0 0.05` | N/A | k- | k- | N/A | I (j) | I (k-) |
| 013 Sag F>>H | j- | `0 -1 0 0.05` | N/A | k | k | N/A | S (j-) | S (k) |

#### NII:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j | `0 1 0 0.05` | `0 1 0 0.05` | j- | j- | j- | P (j) | P (j-) |
| 003 Ax P>>A | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | j | j | j | A (j-) | A (j) |
| 004 Ax R>>L | i | `1 0 0 0.05` | `1 0 0 0.05` | i- | i- | i- | L (i) | L (i-) |
| 005 Ax L>>R | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i | i | i | R (i-) | R (i) |
| 006 Cor R>>L | i | `1 0 0 0.05` | `1 0 0 0.05` | i- | i- | i- | L (i) | L (i-) |
| 007 Cor L>>R | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i | i | i | R (i-) | R(i) |
| 008 Cor H>>F | j | `0 1 0 0.05` | `0 1 0 0.05` | k- | k- | k- | I (j) | I (k-) |
| 009 Cor F>>H | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | k | k | k | S (j-) | S (k) |
| 010 Sag A>>P | i | `1 0 0 0.05` | `1 0 0 0.05` | j- | j- | j- | P (i) | P (j-) |
| 011 Sag P>>A | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | j | j | j | A (i-) | A (j) |
| 012 Sag H>>F | j | `0 1 0 0.05` | `0 1 0 0.05` | k- | k- | k- | I (j) | I (k-) |
| 013 Sag F>>H | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | k | k | k | S (j-) | S (k) |

#### NII with `-strides +1,+2,+3`:

| Acq |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |
| --- | --- | --: | --: | --- | --- | --- | --- | --- |
| 002 Ax A>>P | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | j- | j- | j- | P (j-) | P (j-) |
| 003 Ax P>>A | j | `0 1 0 0.05` | `0 1 0 0.05` | j | j | j | A (j) | A (j) |
| 004 Ax R>>L | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i- | i- | i- | L (i-) | L (i-) |
| 005 Ax L>>R | i | `1 0 0 0.05` | `1 0 0 0.05` | i | i | i | R (i) | R (i) |
| 006 Cor R>>L | i- | `-1 0 0 0.05` | `-1 0 0 0.05` | i- | i- | i- | L (i-) | L (i-) |
| 007 Cor L>>R | i | `1 0 0 0.05` | `1 0 0 0.05` | i | i | i | R (i) | R (i) |
| 008 Cor H>>F | k- | `0 0 -1 0.05` | `0 0 -1 0.05` | k- | k- | k- | I (k-) | I (k-) |
| 009 Cor F>>H | k | `0 0 1 0.05` | `0 0 1 0.05` | k | k | k | S (k) | S (k) |
| 010 Sag A>>P | j- | `0 -1 0 0.05` | `0 -1 0 0.05` | j- | j- | j- | P (j-) | P (j-) |
| 011 Sag P>>A | j | `0 1 0 0.05` | `0 1 0 0.05` | j | j | j | A (j) | A (j) |
| 012 Sag H>>F | k- | `0 0 -1 0.05` | `0 0 -1 0.05` | k- | k- | k- | I (k-) | I (k-) |
| 013 Sag F>>H | k | `0 0 1 0.05` | `0 0 1 0.05` | k | k | k | S (k) | S (k) |

**Review by jdtournier — APPROVED** [review]

**Comment by jdtournier** [comment]
Changes look sensible, tests pass, and you've done way more testing than I can, so let's merge this. :+1:
